config/routes.rb
Bloccit::Application.routes.draw do

  devise_for :users
  resources :users, only: [:update, :show, :index]

  

   resources :topics do
     resources :posts, except: [:index],  controller: 'topics/posts'
   end
 
   resources :posts, only: [:index] do
     resources :comments, only: [:create, :destroy]
     resources :favorites, only: [:create, :destroy]

      post '/up-vote' => 'votes#up_vote', as: :up_vote
      post '/down-vote' => 'votes#down_vote', as: :down_vote
   end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <ul class="nav nav-tabs">
          <li><%= link_to "Bloccit", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Topics", topics_path %></li>
          <li><%= link_to "Popular", posts_path %></li>
          <li><%= link_to "Users", users_path %></li>
      
              <div class="pull-right user-info">
                 <% if current_user %>
                      <%= image_tag(current_user.avatar.tiny.url, class: "img-circle") if current_user.avatar? %>
                          Hello <%= link_to (current_user.name || current_user.email), current_user %>!
                          <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
                            <span class="glyphicon glyphicon-user"></span>
                          <% end %>
                          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
                            <span class="glyphicon glyphicon-log-out"></span>
                          <% end %>
                 <% else %>
                   <%= link_to "Sign In", new_user_session_path %> or
                   <%= link_to "Sign Up", new_user_registration_path %>
                 <% end %>
              </div>

      </ul>

        <% if flash[:notice] %>
           <div class="alert alert-success">
             <button type="button" class="close" data-dismiss="alert">&times;</button>
             <%= flash[:notice] %>
           </div>
         <% elsif flash[:error] %>
           <div class="alert alert-danger">
             <button type="button" class="close" data-dismiss="alert">&times;</button>
             <%= flash[:error] %>
           </div>
         <% elsif flash[:alert] %>
           <div class="alert alert-warning">
             <button type="button" class="close" data-dismiss="alert">&times;</button>
             <%= flash[:alert] %>
           </div>
         <% end %>


      <%= yield %>
    </div>

</body>
</html>